### ISSUE TITLE
Add dependency support

### ISSUE THREAD

**Issue by jeremiah-c-leary** [jeremiah-c-leary/hdl-component-manager#18]
There should be a method to indicate if a block requires another block.
There should also be a way to indicate if a block is not compatible with another block.

I would suggest a yaml file:

``` yaml

requires : 
    rook : 
        url : http://svn/..../rook
        version : 1.0.0

compatibility: 
     castle : 
        url : http://svn/.../castle
        version : 3.2.1

```
